### ISSUE TITLE
Unable to Install on Windows 8

### ISSUE THREAD

**Issue by codelion** [Chris00/ocaml-mindstorm#1]
This library does not work on windows 8, several paths have changed on win8.
In addition win8 platform sdk does not ship with the c/c++ compiler tools so the compiler (cl.exe) has to be downloaded separately as part of Visual Studio 2013 Express Edition.
Currently, we can build the mindstrom_win.lib file but linking any examples with it gives a  LIBCMT not found error. 
EDIT: @reghum has provided more details on the steps we took to build it.

**Comment by Chris00** [comment]
I do not have a win8 box and I do not know what `LIBCMT` is.  Please provide more information and I'll try to help you as best as I can.  First: what instructions do you use to compile the library?

**Comment by reghum** [comment]
Initially, there was some problems in running make and make install like the absence of "cl.exe" ( which required the installation of
windows sdk and the visual studio ); At each run of the make command certain other errors of inability to link with header files like
stddef.h,wtypes.h,etc cropped up. and these involved adding more paths in makefile.win32.

there were other subtle changes like replacing the del command with the rm command.

Right now, the make and make install have been run and the library has been builded; but the make command in the test/examples directory 
are not and hence linking to the mindstorm module has been incapacitated. 

This specific error on LIBCMT happens while invoking make in examples or tests. The LIBCMT file is present in the library of visual studio 11.0 ( though, not in 12.0); but providing it in the path also did not help in removing this error 

![capture](https://cloud.githubusercontent.com/assets/8336087/3787431/68233fcc-1a18-11e4-84be-ea81f9d767ea.JPG)

**Comment by Chris00** [comment]
Where is `LIBCMT` on your system?  What happens if you add the path to the directory where it resides as an additional `-dllpath`?

**Comment by reghum** [comment]
libcmt.lib is present inside the lib directory in visual studio 10.0; but the make did not build successfully,

![capture 1](https://cloud.githubusercontent.com/assets/8336087/3864874/d1c024c6-1f73-11e4-95d8-0093c431518f.PNG)

![capture 2](https://cloud.githubusercontent.com/assets/8336087/3864878/1861f792-1f74-11e4-9049-f0607ffcbc92.PNG)

![capture 4](https://cloud.githubusercontent.com/assets/8336087/3864917/14814608-1f76-11e4-8a77-83b38f179438.PNG)

**Comment by reghum** [comment]
An attempt to install the mindstorm library using oasis was also tried. But the installation of oasis itself was dampened with errors in the installation of prerequisites like ocamlmod : 

![capture](https://cloud.githubusercontent.com/assets/8336087/3875596/ab5eb3f6-2153-11e4-8c8d-7a6ade2f39d7.PNG)

**Comment by Chris00** [comment]
For oasis to work (because it uses `ocamlbuild`), you should remove the compiled files in the source directory.  The script `_build/sanitize.sh` is there to help you (but you have to run it in a bash shell).  Otherwise, just start from a fresh tarball (or ask `git` to remove all non-tracked files).

**Comment by codelion** [comment]
Hi @Chris00,
@reghum has updated the screenshot without the sanitize issue. I think the problem here is that the path constructed by `ocaml setup.ml -configure`  for ocamlfind.exe is loosing the "\" symbol when using -build as you can see in the error `bash:C:OCamlbinocamlfine.EXE : command not found`

**Comment by Chris00** [comment]
Here is a [tarball](http://applications.umons.ac.be/docnum/cb48b103-d14c-4f4d-9a11-117061871f43/d49e48ba-f73c-44bb-964a-d40daa6a8de6/mindstorm-0.5.3.tar.gz) with a `setup.ml` generated by oasis 0.4.5 in case the problem is fixed.

**Comment by Chris00** [comment]
In case that helps you, there was a [Makefile](https://github.com/Chris00/ocaml-mindstorm/blob/75df2acf44b1a22ede1f1ed21481c8a0e43b9255/src/Makefile.WIN32) to compile on Windows.

**Comment by reghum** [comment]
This version of mindstorm got installed properly without any issues, but there was a problem with connecting to the brick using the address, while trying out the example programs. Is there any particular way to do it ?

![capture](https://cloud.githubusercontent.com/assets/8336087/3930025/91085c7c-2433-11e4-82e0-9361381d1bfb.PNG)

**Comment by Chris00** [comment]
When you speak about "this version", do you refer to the tarball or to the Makefile?

**Comment by Chris00** [comment]
About connecting, your screenshot shows an odd bluetooth address.  Please try the instructions in [intro.txt](https://github.com/Chris00/ocaml-mindstorm/blob/master/doc/intro.txt) or, equivalently, read the [documentation](http://ocaml-mindstorm.forge.ocamlcore.org/) on the [website](http://ocaml-mindstorm.forge.ocamlcore.org/index.html).  [I will change the README.md to mention it.]

**Comment by reghum** [comment]
I was referring to the tarball.

**Comment by Chris00** [comment]
OK, great.

**Comment by reghum** [comment]
And it is working with the COM address; I was mistakenly using the 12 byte bluetooth address.. 

![capture1](https://cloud.githubusercontent.com/assets/8336087/3931407/7a7e8624-2457-11e4-83ef-918565a6ae16.PNG)

Thanks a lot !

**Comment by Chris00** [comment]
Glad that it works.  I have updated the [tarball](https://github.com/Chris00/ocaml-mindstorm/releases/tag/0.5.3).

Do not hesitate to share your achievements!

**Comment by reghum** [comment]
Thanks !

**Comment by reghum** [comment]
Hi,

I am able to run the executable files of pre-existing examples and tests; but am not able to compile and create executable files for new programs. I followed this template of commands : 

''C:/OCaml/bin/ocamlfind.EXE ocamldep -package threads -package unix -modules examples/wander.ml >examples/wander.ml.depends               

''C:/OCaml/bin/ocamlfind.EXE ocamlc -c -g -annot -I src -package threads -package unix -thread -I examples -I src -o examples/wander.cmo examples/wander.ml                                                                           

''C:/OCaml/bin/ocamlfind.EXE ocamlopt -c -g -annot -inline 10 -I src -package threads -package unix -thread -I examples -I src -o examples/wander.cmx examples/wander.ml                                                                       

''C:/OCaml/bin/ocamlfind.EXE ocamlopt -g -I src -linkpkg -package unix src/mindstorm.cmxa examples/wander.cmx -o examples/wander.native

Is this right ? I am getting an error of "Unbound module" with the ocalmc command : 

![capture](https://cloud.githubusercontent.com/assets/8336087/3947601/69c725b2-2690-11e4-80c3-f90606398843.PNG)

**Comment by Chris00** [comment]
`ocamldep` generates Makefile rules to let `make` know about the dependencies of your module.  Since you (seem to) write the compilations command yourself, this is unecessary.

**Comment by Chris00** [comment]
> ocamlfind.EXE ocamlopt -g -I src -linkpkg -package unix src/mindstorm.cmxa examples/wander.cmx -o examples/wander.native

You can pass directly from the `.ml` file to the `.native` one.  Just compile without the `-c` flag.  Please read the part of the manual about the compilers.

**Comment by Chris00** [comment]
You cannot use the same recipies as the ones for the compilation of the examples of the library.  These rules try to compile the examples _without_ installing the library.

Assuming you installed the library, you should be able to use something like `ocamlfind ocamlc -annot -o motor1.exe -package mindstorm -linkpkg motor1.ml`

**Comment by reghum** [comment]
Thanks a lot !
